modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="hashiriyacarmod"
version="1.0.0"
displayName="Hashiriya Car Mod"
authors="shimo"
description='''
Test mod for realistic car behavior in Minecraft 1.20.1.
'''
[[dependencies.hashiriyacarmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.hashiriyacarmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"